"""init master schema

Revision ID: dc70dbbcf28a
Revises:
Create Date: 2026-08-27 23:44:16.528362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc70dbbcf28a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("additional_phone", sa.String(length=32), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="gender", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("middle_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_administrators")),
        sa.UniqueConstraint("email", name=op.f("uq_administrators_email")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_administrators_telegram_user_id")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("additional_phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="gender", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("card_number", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "vip",
                "regular",
                "new",
                "inactive",
                name="clientcategory",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum("high", "medium", "low", name="clientimportance", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("no_online_booking", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("middle_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("phone", name=op.f("uq_clients_phone")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_clients_telegram_user_id")),
    )
    op.create_table(
        "masters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("additional_phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="gender", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("middle_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_masters")),
        sa.UniqueConstraint("email", name=op.f("uq_masters_email")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_masters_telegram_user_id")),
    )
    op.create_table(
        "salons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("db_host", sa.String(length=255), nullable=False),
        sa.Column("db_port", sa.Integer(), nullable=False),
        sa.Column("db_name", sa.String(length=64), nullable=False),
        sa.Column("db_user", sa.String(length=64), nullable=False),
        sa.Column("secret_env", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "provisioning",
                "active",
                "suspended",
                name="salonstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salons")),
        sa.UniqueConstraint("slug", name=op.f("uq_salons_slug")),
    )
    op.create_table(
        "administrator_salons",
        sa.Column("administrator_id", sa.Uuid(), nullable=False),
        sa.Column("salon_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["administrator_id"],
            ["administrators.id"],
            name=op.f("fk_administrator_salons_administrator_id_administrators"),
        ),
        sa.ForeignKeyConstraint(
            ["salon_id"], ["salons.id"], name=op.f("fk_administrator_salons_salon_id_salons")
        ),
        sa.PrimaryKeyConstraint(
            "administrator_id", "salon_id", name=op.f("pk_administrator_salons")
        ),
    )
    op.create_table(
        "master_salons",
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("salon_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["master_id"], ["masters.id"], name=op.f("fk_master_salons_master_id_masters")
        ),
        sa.ForeignKeyConstraint(
            ["salon_id"], ["salons.id"], name=op.f("fk_master_salons_salon_id_salons")
        ),
        sa.PrimaryKeyConstraint("master_id", "salon_id", name=op.f("pk_master_salons")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("master_salons")
    op.drop_table("administrator_salons")
    op.drop_table("salons")
    op.drop_table("masters")
    op.drop_table("clients")
    op.drop_table("administrators")
    # ### end Alembic commands ###
