"""init shard schema

Revision ID: 686c98e38627
Revises:
Create Date: 2026-08-27 23:44:18.088919

ВАЖНО: миграция прогоняется на все шард-БД неатомарно — она обязана быть
backward-compatible (expand → migrate → contract).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "686c98e38627"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "created", "updated", "deleted", name="auditaction", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_created", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_entity", "audit_log", ["entity", "entity_id"], unique=False)
    op.create_table(
        "cash_registers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_registers")),
    )
    op.create_table(
        "finance_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "receipt",
                "invoice",
                "expense",
                "income",
                "act",
                name="documenttype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "services",
                "products",
                "mixed",
                name="documentcontenttype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("counterparty", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "paid",
                "cancelled",
                name="documentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_documents")),
        sa.UniqueConstraint("number", name=op.f("uq_finance_documents_number")),
    )
    op.create_table(
        "outbox",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_outbox")),
    )
    op.create_index("ix_outbox_unpublished", "outbox", ["published_at", "created_at"], unique=False)
    op.create_table(
        "schedule_exceptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "vacation",
                "sick",
                "day_off",
                "extra_shift",
                name="scheduleexceptiontype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_exceptions")),
    )
    op.create_index(
        op.f("ix_schedule_exceptions_master_id"), "schedule_exceptions", ["master_id"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "inactive", "archived", name="servicestatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "staff_profiles",
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=128), nullable=True),
        sa.Column("specializations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "vacation",
                "sick",
                "fired",
                name="staffstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("salary", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("commission_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column("fired_at", sa.Date(), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("master_id", name=op.f("pk_staff_profiles")),
    )
    op.create_table(
        "staff_schedules",
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("is_work_day", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("break_start", sa.Time(), nullable=True),
        sa.Column("break_end", sa.Time(), nullable=True),
        sa.PrimaryKeyConstraint("master_id", "weekday", name=op.f("pk_staff_schedules")),
    )
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "cash",
                "card",
                "online",
                "certificate",
                "bonus",
                "tips",
                "other",
                name="paymentmethodtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("cash_register_id", sa.Uuid(), nullable=True),
        sa.Column(
            "commission_type",
            sa.Enum(
                "none", "percentage", "fixed", name="commissiontype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("commission_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "commission_payer",
            sa.Enum(
                "client", "salon", "split", name="commissionpayer", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("available_online", sa.Boolean(), nullable=False),
        sa.Column("allow_partial_payment", sa.Boolean(), nullable=False),
        sa.Column("allow_tips", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cash_register_id"],
            ["cash_registers.id"],
            name=op.f("fk_payment_methods_cash_register_id_cash_registers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
    )
    op.create_table(
        "records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "confirmed",
                "arrived",
                "completed",
                "cancelled",
                "no_show",
                name="recordstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "admin",
                "booking",
                "bot",
                "phone",
                "walk_in",
                name="recordsource",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "unpaid", "partial", "paid", name="paymentstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum(
                "standard",
                "important",
                "special",
                name="recordimportance",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_phone", sa.String(length=32), nullable=False),
        sa.Column("master_name", sa.String(length=255), nullable=False),
        sa.Column("visitor_name", sa.String(length=255), nullable=True),
        sa.Column("visitor_phone", sa.String(length=32), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("internal_notes", sa.String(length=4000), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_by_name", sa.String(length=255), nullable=True),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("closed_by_name", sa.String(length=255), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_token", sa.Uuid(), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_records_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_records")),
        sa.UniqueConstraint("review_token", name=op.f("uq_records_review_token")),
    )
    op.create_index(op.f("ix_records_client_id"), "records", ["client_id"], unique=False)
    op.create_index("ix_records_master_start", "records", ["master_id", "start_at"], unique=False)
    op.create_index(
        "ix_records_reminder_scan", "records", ["start_at", "reminder_sent_at"], unique=False
    )
    op.create_table(
        "service_masters",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_service_masters_service_id_services")
        ),
        sa.PrimaryKeyConstraint("service_id", "master_id", name=op.f("pk_service_masters")),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cash_register_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("record_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "paid", "partial", "cancelled", name="receiptstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("web", "mobile", "pos", name="receiptsource", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cash_register_id"],
            ["cash_registers.id"],
            name=op.f("fk_receipts_cash_register_id_cash_registers"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["finance_documents.id"],
            name=op.f("fk_receipts_document_id_finance_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["records.id"], name=op.f("fk_receipts_record_id_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("number", name=op.f("uq_receipts_number")),
    )
    op.create_table(
        "record_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["records.id"], name=op.f("fk_record_photos_record_id_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_record_photos")),
    )
    op.create_index(
        op.f("ix_record_photos_record_id"), "record_photos", ["record_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("master_name", sa.String(length=255), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=4000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["record_id"], ["records.id"], name=op.f("fk_reviews_record_id_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("record_id", name=op.f("uq_reviews_record_id")),
    )
    op.create_index(op.f("ix_reviews_client_id"), "reviews", ["client_id"], unique=False)
    op.create_index(op.f("ix_reviews_master_id"), "reviews", ["master_id"], unique=False)
    op.create_table(
        "finance_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "income", "expense", "transfer", name="operationtype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "pending",
                "cancelled",
                name="operationstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("cash_register_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("record_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cash_register_id"],
            ["cash_registers.id"],
            name=op.f("fk_finance_operations_cash_register_id_cash_registers"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["finance_documents.id"],
            name=op.f("fk_finance_operations_document_id_finance_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_finance_operations_payment_method_id_payment_methods"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], name=op.f("fk_finance_operations_receipt_id_receipts")
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["records.id"], name=op.f("fk_finance_operations_record_id_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_operations")),
    )
    op.create_index("ix_finance_operations_date", "finance_operations", ["date"], unique=False)
    op.create_table(
        "receipt_payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_receipt_payments_payment_method_id_payment_methods"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], name=op.f("fk_receipt_payments_receipt_id_receipts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_payments")),
    )
    op.create_index(
        op.f("ix_receipt_payments_receipt_id"), "receipt_payments", ["receipt_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_payments_receipt_id"), table_name="receipt_payments")
    op.drop_table("receipt_payments")
    op.drop_index("ix_finance_operations_date", table_name="finance_operations")
    op.drop_table("finance_operations")
    op.drop_index(op.f("ix_reviews_master_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_client_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_record_photos_record_id"), table_name="record_photos")
    op.drop_table("record_photos")
    op.drop_table("receipts")
    op.drop_table("service_masters")
    op.drop_index("ix_records_reminder_scan", table_name="records")
    op.drop_index("ix_records_master_start", table_name="records")
    op.drop_index(op.f("ix_records_client_id"), table_name="records")
    op.drop_table("records")
    op.drop_table("payment_methods")
    op.drop_table("staff_schedules")
    op.drop_table("staff_profiles")
    op.drop_table("settings")
    op.drop_table("services")
    op.drop_index(op.f("ix_schedule_exceptions_master_id"), table_name="schedule_exceptions")
    op.drop_table("schedule_exceptions")
    op.drop_index("ix_outbox_unpublished", table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("finance_documents")
    op.drop_table("cash_registers")
    op.drop_index("ix_audit_entity", table_name="audit_log")
    op.drop_index("ix_audit_created", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
