/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppForbiddenRouteImport } from './routes/_app/forbidden'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as BookingSlugIndexRouteImport } from './routes/booking/$slug/index'
import { Route as BookingSlugReviewRouteImport } from './routes/booking/$slug/review'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppForbiddenRoute = AppForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugIndexRoute = BookingSlugIndexRouteImport.update({
  id: '/booking/$slug/',
  path: '/booking/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugReviewRoute = BookingSlugReviewRouteImport.update({
  id: '/booking/$slug/review',
  path: '/booking/$slug/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/finances': typeof AppFinancesRoute
  '/forbidden': typeof AppForbiddenRoute
  '/inventory': typeof AppInventoryRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/booking/': typeof BookingIndexRoute
  '/booking/$slug/review': typeof BookingSlugReviewRoute
  '/booking/$slug/': typeof BookingSlugIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/finances': typeof AppFinancesRoute
  '/forbidden': typeof AppForbiddenRoute
  '/inventory': typeof AppInventoryRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/': typeof AppIndexRoute
  '/booking': typeof BookingIndexRoute
  '/booking/$slug/review': typeof BookingSlugReviewRoute
  '/booking/$slug': typeof BookingSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/forbidden': typeof AppForbiddenRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/': typeof AppIndexRoute
  '/booking/': typeof BookingIndexRoute
  '/booking/$slug/review': typeof BookingSlugReviewRoute
  '/booking/$slug/': typeof BookingSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/clients'
    | '/finances'
    | '/forbidden'
    | '/inventory'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/booking/'
    | '/booking/$slug/review'
    | '/booking/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/clients'
    | '/finances'
    | '/forbidden'
    | '/inventory'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/'
    | '/booking'
    | '/booking/$slug/review'
    | '/booking/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/calendar'
    | '/_app/clients'
    | '/_app/finances'
    | '/_app/forbidden'
    | '/_app/inventory'
    | '/_app/overview'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/staff'
    | '/_app/'
    | '/booking/'
    | '/booking/$slug/review'
    | '/booking/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BookingIndexRoute: typeof BookingIndexRoute
  BookingSlugReviewRoute: typeof BookingSlugReviewRoute
  BookingSlugIndexRoute: typeof BookingSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forbidden': {
      id: '/_app/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AppForbiddenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug/': {
      id: '/booking/$slug/'
      path: '/booking/$slug'
      fullPath: '/booking/$slug/'
      preLoaderRoute: typeof BookingSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug/review': {
      id: '/booking/$slug/review'
      path: '/booking/$slug/review'
      fullPath: '/booking/$slug/review'
      preLoaderRoute: typeof BookingSlugReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppForbiddenRoute: typeof AppForbiddenRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppForbiddenRoute: AppForbiddenRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppStaffRoute: AppStaffRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BookingIndexRoute: BookingIndexRoute,
  BookingSlugReviewRoute: BookingSlugReviewRoute,
  BookingSlugIndexRoute: BookingSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
